### ISSUE TITLE
Change reliance on client_id to identify the Provider and Client

### ISSUE THREAD

**Issue by kjgarza** [datacite/viringo#53] opened 2020-05-11 14:01 UTC
related: https://github.com/datacite/datacite/issues/1008

**Comment by richardhallett** [comment] 2020-05-15 13:29
@kjgarza Do you have a suggested way to retrieve the "provider id" (member id) going forward? Looking back on this now, the reason this was done is this information is not available in the API requests to DOIS, it only specifies the "client" (repository)?

I'd be reluctant to end up calling the API again just to find out the member id.

This is needed because in OAIPMH land we have "sets" (the unique groups) who hold the DOIs, so in our case we used to have this split by "provider/client". So you can say "Show me all DOI's for all BL dois"

Thoughts?

**Comment by kjgarza** [comment] 2020-05-15 13:41
Unfortunately I have not suggestions. But should be able to get provider from the relationships. Maybe changing the Lupo API

**Comment by richardhallett** [comment] 2020-05-15 13:48
@mfenner What are your thoughts on this? Do you think it'd be feasible to add providers to the relationships of the dois e.g. under /dois endpoint on lupo?

I guess dois only have a direct relationship to clients (repositories) and not to providers (members) so that's why it doesn't appear on the endpoint currently.

**Comment by mfenner** [comment] 2020-05-15 14:40
Provider and client metadata are indexed with every DOI, take a look at the schema.

**Comment by richardhallett** [comment] 2020-10-30 14:42
This has started to cause issues so im labeling as a bug.

There are two problems here
1.

Currently is if you try to use a set that has been transferred to a new provider it splits this into provider_id and client_id and sends this to the API, this now then of course finds nothing e.g.
https://oai.datacite.org/oai?verb=ListRecords&set=delft.uu&metadataPrefix=oai_datacite
goes to
https://api.datacite.org/dois?client_id=delft.uu&provider_id=delft

The solution to this part of the problem is I can avoid sending provider_id as it's not needed when retrieving records.
However it leads onto second problem

2. The header information of individual records lists "sets" and one of the sets is the "provider" the other is the client, with transfers this is now going to have the wrong data.
Code is here:
https://github.com/datacite/viringo/blob/24dda9ecb99234fec3d39a7ca1e4ac1cb1580766/viringo/catalogs.py#L218

This could be solved with above conversation regarding changing API to return the provider, perhaps under the details flag.
Alternative solution would be to just remove provider listings entirely, however this would be a significant change and potentially break existing implementations that do require this functionality.

**Comment by richardhallett** [comment] 2020-11-05 14:47
This was fixed by changing the API to return provider id in the response, now it is correctly parsed and we no longer guess the provider/client ids.

**Closed by richardhallett** 2020-11-05 14:47 UTC
Labels: bug
